More accurate/descriptive error messages for start_traj_mode and start_point_queue_mode services
Yaskawa-Global/motoros2 pull request #265
Opened 2024-06-19 19:21 UTC by jimmy-mcelwain

In reference to #37 and #192. Now the error message and error codes match the reasons that the motion start failed.

2024-06-19 19:30 UTC, jimmy-mcelwain commented
Dependent upon https://github.com/Yaskawa-Global/motoros2_interfaces/pull/17

2024-06-24 08:25 UTC, gavanderhoorn commented
High-level comment (about the proposed approach): the current implementation seems to use a different approach: error reporting uses the result of `Ros_Controller_GetNotReadySubcode()` (based on the result of `Ros_Controller_IsMotionReady()`) if `Ros_MotionControl_StartMotionMode(..)` (or anything else) failed.

The current approach is slightly racy (as in: noticing *something* was wrong and reporting about *what* was wrong are done at different times -- but so far that hasn't really been problematic), but the proposed approach starts mixing responsibilities. It also duplicates quite a bit of code.

Perhaps we should try and find a middle-ground?

2024-06-24 08:32 UTC, gavanderhoorn commented
And another (but only slightly related to this PR): seems the new error / pattern matcher in combination with the updated `mpBuilder` doesn't yet capture compiler errors correctly, resulting in the many incomplete annotations.

I'll look into this and fix it.

2024-06-25 15:51 UTC, jimmy-mcelwain commented
@gavanderhoorn This is sort of an awkward responsibility-mixing design. I was trying to solve the issue without any sort of big redesign of how `Ros_Controller_GetNotReadySubcode()` is used. 

I do think that the current way that errors are reported, by noticing that there is an issue, and then trying to identify that issue later based on the state of the controller, seems likely to cause to problems/makes it difficult to get useful error messages. I think that a more direct error-reporting approach may be more reliable/less 'racy', but yeah there would be more code duplication. 

More significant changes would need to be made to get rid of the responsibility-mixing aspect, or I could move closer to the original approach. but I don't know what the best option is. I pushed some minor changes that make it a bit cleaner, but didn't change the approach.

2024-06-27 19:03 UTC, ted-miller requested changes
I'm also not a big fan of the repeated code.

What if in `Ros_MotionControl_StartMotionMode`, the first thing you do is call `Ros_Controller_GetNotReadySubcode`? If it returns a code that cannot be resolved by the actions of this function (like estop or play-mode), then return that code immediately. That should remove some of the duplication.

I expect that such an approach would also need to ensure that things are checked in a particular order within `Ros_Controller_GetNotReadySubcode`. (Unresolvable issues checked first)

2024-06-27 19:03 UTC, ted-miller commented on src/MotionControl.c
> +    char output[256] = { 0 };
The `256` needs to be a named constant. It is used in multiple places below.

Additionally, I'm not sure that the `output` buffer is really needed. If things are checked in the correct order, then `Ros_ErrorHandling_MotionNotReadyCode_ToString` should contain sufficient information to the user _(I think)_. In that case, you shouldn't need to pass in the pointer to `responseMessage`.

Do you have some example strings from testing that you can post?

2024-08-29 15:58 UTC, closed without merging